name: 'Smoke test'
inputs:
  image:
    description: 'Image to test'
    required: true
  repo-token:
    description: github token
    required: true

runs:
  using: composite
  steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.repo-token }}

    - name: Checkout main
      id: checkout_release
      uses: actions/checkout@v3

    - name: Build image
      id: build_image
      shell: bash
      run: ${{ github.action_path }}/build.sh ${{ inputs.image }}

    - name: Test image
      id: test_image
      shell: bash
      run: ${{ github.action_path }}/test.sh  ${{ inputs.image }}
