name: "Release Dev Container Images"
on:
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with: 
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Smoke test for 'base-ubuntu'
        id: smoke_test_base_ubuntu
        uses: ./.github/actions/smoke-test
        with:
          image: "base-ubuntu"
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
      
      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          subFolder: ./src/base-ubuntu
          imageName: ghcr.io/meastp/images/base-ubuntu
          skipContainerUserIdUpdate: true
          push: always
      
      - name: Smoke test for 'cpp'
        id: smoke_test_cpp
        uses: ./.github/actions/smoke-test
        with:
          image: "cpp"
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
      
      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          subFolder: ./src/base-ubuntu
          imageName: ghcr.io/meastp/images/cpp
          skipContainerUserIdUpdate: true
          push: always
