name: "Release Dev Container Images"
on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        required: true
        description: image to test, build, push
        options:
        - base-ubuntu
        - cpp

jobs:
  test:
    if: ${{ github.ref == 'refs/heads/main' }}
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Smoke test
        id: smoke_test
        uses: ./.github/actions/smoke-test
        with:
          image: "${{ github.event.inputs.name }}"
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with: 
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          subFolder: ./src/${{ github.event.inputs.name }}
          imageName: ghcr.io/meastp/images/${{ github.event.inputs.name }}
          skipContainerUserIdUpdate: true
          push: always
